"""End-to-end smoke tests for the real headless composition (Phase 1).

Everything else is unit-tested with fakes; these exercise the *glue* the unit
tests stub out:

* ``test_build_repo_real_roundtrip`` runs the real ``cli._build_repo()`` against
  a temp DB + key file (real ``init_db``/``session_factory``/``SecretBox``/Fernet
  + Alembic migrations) — it catches signature drift the monkeypatched CLI tests
  cannot.
* ``test_headless_pipeline_fires_plex_scan`` (Linux-only) wires a real ``Repo`` →
  real ``InotifyBackend`` → real ``Engine`` → real ``PlexAdapter`` and asserts a
  file landing on disk drives a correctly-targeted Plex partial scan, with the
  outbound HTTP intercepted by respx (no real Plex needed).
"""

import asyncio
import sys
from pathlib import Path

import httpx
import pytest
import respx

from mediascanmonitor import cli as cli_module
from mediascanmonitor.db.models import DebounceMode, ScanMode, ServerType
from mediascanmonitor.db.schemas import FolderCreate, ServerCreate
from mediascanmonitor.engine import Engine, EngineState
from mediascanmonitor.watcher.inotify_backend import InotifyBackend
from tests._helpers import wait_for

BASE = "http://plex.example:32400"


def test_build_repo_real_roundtrip(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # Point the real _build_repo at throwaway paths; no MSM_SECRET_KEY so a fresh
    # key file is generated by load_or_create_key.
    monkeypatch.setenv("MSM_DB_PATH", str(tmp_path / "app.db"))
    monkeypatch.setenv("MSM_SECRET_KEY_FILE", str(tmp_path / "secret.key"))
    monkeypatch.delenv("MSM_SECRET_KEY", raising=False)

    repo = cli_module._build_repo()

    # A secret survives the real Fernet encrypt -> store -> decrypt round-trip,
    # which only works if init_db ran the migrations and the box key loaded.
    server = repo.create_server(
        ServerCreate(name="plex", type=ServerType.plex, base_url=BASE, secret="TOK-123")
    )
    assert repo.resolve_secret(server) == "TOK-123"

    repo.set_setting("inotify_gate", "off")
    assert repo.get_setting("inotify_gate") == "off"


@pytest.mark.skipif(sys.platform != "linux", reason="real inotify backend is Linux-only")
@respx.mock
async def test_headless_pipeline_fires_plex_scan(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("MSM_DB_PATH", str(tmp_path / "app.db"))
    monkeypatch.setenv("MSM_SECRET_KEY_FILE", str(tmp_path / "secret.key"))
    monkeypatch.delenv("MSM_SECRET_KEY", raising=False)

    repo = cli_module._build_repo()
    repo.set_setting("inotify_gate", "off")  # deterministic: don't depend on host /proc

    # A real media tree; the show folder pre-exists so it is watched at set_roots
    # (no dynamic-subdir timing to race).
    media = tmp_path / "media" / "tv"
    show = media / "Shoresy"
    show.mkdir(parents=True)

    server = repo.create_server(
        ServerCreate(
            name="plex",
            type=ServerType.plex,
            base_url=BASE,
            secret="TOK-123",
            scan_mode=ScanMode.targeted,
            debounce_mode=DebounceMode.off,  # immediate dispatch -> no clock to advance
        )
    )
    assert server.id is not None
    repo.create_folder(
        server.id,
        FolderCreate(path=str(media), library_id="2", extensions=["mkv"]),
    )

    route = respx.get(f"{BASE}/library/sections/2/refresh").mock(return_value=httpx.Response(200))

    engine = Engine(repo, watcher=InotifyBackend(frozenset({"@eaDir", "#snapshot"})))
    start_task = asyncio.create_task(engine.start())
    try:
        await wait_for(lambda: engine.state is EngineState.running, timeout=5.0)

        (show / "s01e01.mkv").write_text("x")  # the real filesystem event

        await wait_for(lambda: route.called, timeout=5.0)

        request = route.calls.last.request
        assert request.headers["X-Plex-Token"] == "TOK-123"
        assert "TOK-123" not in str(request.url)  # token in header, never the URL
        assert request.url.params["path"] == str(show)  # targeted at the show folder
    finally:
        await engine.aclose()
        await start_task
